<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '智能家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '2',
    'name' => '智能家居',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '配件优选',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '配件优选',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '手机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 0,
    'id' => '1',
    'name' => '手机',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '三星',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '5',
    'name' => '三星',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '小米',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '6',
    'name' => '小米',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '苹果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '98',
    'level' => 1,
    'id' => '4',
    'name' => '苹果',
  ),
);
?>