<?php
$data = array (
  0 => 
  array (
    'cat_id' => '9',
    'cat_name' => '索尼',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '6',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '7',
    'cat_name' => '佳能',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '6',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '1',
  ),
  2 => 
  array (
    'cat_id' => '8',
    'cat_name' => '尼康',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '6',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '16',
    'cat_name' => '单反相机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '18',
    'cat_name' => '镜头组',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '17',
    'cat_name' => '专业单反相机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '13',
    'cat_name' => '单反相机',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '10',
    'cat_name' => '数码相机',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  8 => 
  array (
    'cat_id' => '14',
    'cat_name' => '拍立得',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '96',
  ),
  9 => 
  array (
    'cat_id' => '11',
    'cat_name' => '单电',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  10 => 
  array (
    'cat_id' => '12',
    'cat_name' => '微单相机',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  11 => 
  array (
    'cat_id' => '21',
    'cat_name' => '入门级单反相机',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  12 => 
  array (
    'cat_id' => '19',
    'cat_name' => '摄像机系列',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '22',
    'cat_name' => '入门单反相机',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '15',
    'cat_name' => '产品摄影附件',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  15 => 
  array (
    'cat_id' => '23',
    'cat_name' => '对焦，留住，抓紧那刻仅有的心情',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '20',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => '3',
  ),
);
?>